### ISSUE TITLE
[1.15.2] Mekanism pipe render glitch

### ISSUE THREAD

**Issue by elowanut** [qouteall/ImmersivePortalsModForForge#92]
**Forge:**  forge-1.15.2-31.1.74
**Immersive Portals:** immersive-portals-0.17(forMc1.15withForge)
**Mixin:** MixinBootstrap-1.0.3
**Mekanism:** Mekanism-1.15.2-9.10.2.415

I'm experiencing a strange glitch when you combine IP (for forge) with Mekanism. With IP installed, Mekanism pipes eventually visually glitch to be displayed vertically, instead of their original placement (e.g. you can make a long horizontal network of pipes, and after a while, they glitch so that each segment looks like it is individually vertical.) The glitch doesn't occur instantly (you can place pipes normally, and they stay that way for a while.

Edit: To be clear, this seems to be similar to #49 , but it's definitely still happening.  

Here is a before (with Mekanism etc., but no IP) pic:
![javaw_2020-05-05_15-33-14](https://user-images.githubusercontent.com/55150170/81109072-8a790d00-8ee7-11ea-89ac-9098ba5e305e.jpg)
Here is an after (with IP) pic:
![javaw_2020-05-05_15-44-24](https://user-images.githubusercontent.com/55150170/81109145-a7addb80-8ee7-11ea-8e03-89e9b4a78def.jpg)

Note that simply installing IP doesn't do this. You need to create a live IP portal. In this case, I have an IP nether portal ~20-30 blocks away. It's possible that mekanism pipes that are nowhere near IP portals might not be affected, I haven't tested that.

Keep in mind that this is a _visual glitch only_. The pipes continue to pass energy and items through them (you can see the "beam" of energy in my after pic).

**Comment by qouteall** [comment]
I found another hacky way to fix this issue.
It's may be radically fixed in the next version

**Comment by qouteall** [comment]
fixed

**Comment by nerdywhiteguy** [comment]
I can confirm that this issue persists in 1.16.1.
- immersive-portals-0.2-mc1.16.1-forge
- Mekanism-1.16.1-10.0.9.432
- Forge 32.0.108

I also get "dark chunks" sometimes where everything within a few chunks of the portal would render as if it were not illuminated unless the block itself were producing light or was getting direct sunlight.
![Screenshot](https://user-images.githubusercontent.com/1589227/93007518-89ec2500-f51e-11ea-83ba-d820c4c3b770.png)
Once, my line of vanilla chests attached to colored Logistical Transporters became invisible and only opening each chest made it appear again.

**Comment by Oct0bass** [comment]
Wierd how the pumpkins don't seem to be affected :laughing:.
